"""Update creator field to string

Revision ID: 2a5ce7303c42
Revises: e8272c10980f
Create Date: 2023-03-04 17:50:01.563345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5ce7303c42'
down_revision = 'e8272c10980f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
