"""Update creator field to string

Revision ID: 50ca70f40a05
Revises: df0f8a689d7b
Create Date: 2023-03-04 17:46:50.931580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ca70f40a05'
down_revision = 'df0f8a689d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
