"""Update creator field to int

Revision ID: 86435bd8691b
Revises: 92f1ed079557
Create Date: 2023-03-04 18:03:18.085478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86435bd8691b'
down_revision = '92f1ed079557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
