"""Update creator field to string

Revision ID: 92f1ed079557
Revises: 2a5ce7303c42
Create Date: 2023-03-04 17:57:20.409507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f1ed079557'
down_revision = '2a5ce7303c42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
